name: Terraform CI/CD (seoul)

on:
  push:
    branches: [main]
    paths:
      - 'seoul/**'       # seoul 디렉토리 변경 시에만 실행

permissions:
  id-token: write        # OIDC 토큰 발급 허용
  contents: read

jobs:
  terraform:
    name: Terraform Apply - Seoul
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: seoul        # 실행 디렉토리?

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::539247452332:role/githubActions_terraform
          aws-region: ap-northeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="seoul.tfvars" -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -var-file="seoul.tfvars" -auto-approve -input=false
